import React from "react";
import Head from "next/head";
import Layout from "../layout";
import GlobalStyle from "../styles/global";

function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>르네상스랩스 프론트엔드 개발자 사전과제</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/renaissance-lab-logo.webp" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
      <GlobalStyle />
    </>
  );
}

export default App;
