import React from "react";
import Head from "next/head";
import Layout from "../layout";
import GlobalStyle from "../styles/global";
import { AppProps } from "next/app";
import { Web3ReactProvider } from "@web3-react/core";
import { Web3Provider } from "@ethersproject/providers";
import Web3 from "web3";

declare global {
  interface Window {
    web3?: Web3;
  }
}

function App({ Component, pageProps }: AppProps) {
  function getLibrary(provider) {
    const library = new Web3Provider(provider, "any");
    return library;
  }
  return (
    <>
      <Head>
        <title>르네상스랩스 프론트엔드 개발자 사전과제</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/renaissance-lab-logo.webp" />
      </Head>
      <Web3ReactProvider getLibrary={getLibrary}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </Web3ReactProvider>
      <GlobalStyle />
    </>
  );
}

export default App;
